### ISSUE TITLE
Twerking Progress (Suggestion)

### ISSUE THREAD

**Issue by SpeedSlider** [AllTheMods/ATM3-Skyblock#13]
Is there a way to increase the rate at which saplings grow by twerking. The initial sapling seems to take a lot of shifting to grow.

**Comment by kjmaster1** [comment]
It would be great if saplings just grew faster by default without any input at all. Means you don't have to sit there spamming sneak or wasting food sprinting. Makes early auto tree farms a bit more effective too.

**Comment by Boomflex** [comment]
Early game isnt supposed to be efficient or effective.

Twerking is random, I've had it work on first couple or take 1 min...

RNGesus be against you.

**Comment by kjmaster1** [comment]
Fair enough, there's always good ole bonemeal anyway.
