### ISSUE TITLE
Enchantments on Sieve Mesh

### ISSUE THREAD

**Issue by FallenEagle1** [AllTheMods/ATM3-Skyblock#22]
ATM:SE 0.3
As the pack stands now, it jei shows that there are three different enchants that can be put onto sieve meshes; sieve fortune, sieve luck of the sea, and sieve efficiency. However, when a mesh is put into an enchanting table, no enchants are brought up.

**Comment by BloodWorkXGaming** [comment]
Fixed in ex creatio update, or you could use books to get them :P

FallenEagle1 <notifications@github.com> schrieb am Sa., 21. Apr. 2018,
18:27:

**Comment by FallenEagle1** [comment]
Didn't see a good way to get the books except hope for the best, but if it's fixed that's good to know.
