### ISSUE TITLE
Ex Nihilo: Creatio ore pieces craft directly to ores instead of chunks.

### ISSUE THREAD

**Issue by SpeedSlider** [AllTheMods/ATM3-Skyblock#4]
Ore pieces craft directly to their ore counterpart and there does not seem to be a recipe for the ore chunks. This is usually the intermediate step to ore (e.g 4 iron ore pieces make 1 iron ore chunk and 4 iron ore chunks make 1 iron ore). Considering where ATM3 is it doesn't make sense to skip this step.

I do realize that Ex Nihilo: Creatio is in alpha state.

**Comment by BloodWorkXGaming** [comment]
There is a fix for that in my dev envo, will release it on Monday or
Tuesday or somewhere around that.

SpeedSlider <notifications@github.com> schrieb am Fr., 13. Apr. 2018, 01:42:

**Comment by SpeedSlider** [comment]
Issue resolved in latest version of ATM3-SE
